spring:
  proflies:
    active: dev

---
server:
  port: 8861
mybatis:
  type-aliases-package: com.zs.cloud.pojo
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml

spring:
  profiles: dev
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/user?useUnicode=true&characterEncodeing=UTF-8&useSSL=false&serverTimezone=GMT&allowPublicKeyRetrieval=true
    username: root
    password: 123456

eureka:
  client:
    service-url:
      #      集群部署
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: provider-8862 #修改eureka中status信息
    prefer-ip-address: true #展示真实ip地址
info:
  app.name: springcloud-provider
feign:
  hystrix:
    enabled: true
